name: Continuous Integration

on:
  push:
    branches: ['**']

jobs:
  ci:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Run Conventional Commits check
        uses: webiny/action-conventional-commits@v1.3.0

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup dotnet 9.x
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      - name: Build
        shell: pwsh
        run: dotnet build --configuration Release
